# Análisis de datos cualitativos

## Introducción a Python

### Variables y operaciones básicas

In [3]:
var = "Bienvenidos al curso de analisis de datos cualitativos"

var1 = 12
var2 = 23

var1 + var2
var1 - var2

-11

### Tipos de datos

En Python, los tipos de datos básicos incluyen:

- Enteros (int): Representan números enteros, positivos o negativos, sin parte decimal. Por ejemplo: 5, -10, 1000.

- Flotantes (float): Representan números reales con parte decimal. Por ejemplo: 3.14, 2.718, 10.0.

- Booleanos (bool): Representan valores de verdad, es decir, verdadero (True) o falso (False). Se utilizan en operaciones lógicas y de control de flujo.

- Cadenas de caracteres (str): Representan secuencias de caracteres, como texto. Se pueden definir utilizando comillas simples (') o dobles ("). Por ejemplo: 'Hola mundo', "Python es genial".

### Estructuras de datos

In [23]:
# Listas
lista = [1, 2, 3, 4, 5]
lista.append(6)
lista.remove(1)
a = lista[0]

# Diccionarios
data = {
    "a": 1,
    "b": 2,
    "c": 3
}
data.get("d", 0)

# Sets (conjuntos)
set1 = set([1, 2, 1, 3])
set2 = set([3, 4, 5, 6])
set3 = set2 - set1
set3

# Tuplas
tupla = (1, 2, 3)
tupla

# Las tuplas pueden ser claves en diccionarios.
d1 = {
    tupla: "mi primer tupla"
}

### Loops y condicionales

In [32]:
for a in data:
  value = data[a]
  print(f"El valor {value} esta asociado a la clave {a}")

El valor 1 esta asociado a la clave a
El valor 2 esta asociado a la clave b
El valor 3 esta asociado a la clave c


In [34]:
for key, value in data.items():
  print(f"El valor {value} está asociado a la clave {key}")

El valor 1 está asociado a la clave a
El valor 2 está asociado a la clave b
El valor 3 está asociado a la clave c


In [35]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [38]:
var1 = 10
if var1 > 10:
  print("La variable es mayor a 10")
else:
  print("La variable es menor o igual a 10")

La variable es menor o igual a 10


### Funciones y funciones anónimas

#### Funciones explicitas

In [40]:
var1 = 5

def elevar_al_cuadrado(n):
  return n**2

elevar_al_cuadrado(var1)

25

#### Funciones anónimas

In [43]:
fn = lambda n: n**2
fn(2)

4

### Clases y objetos

En la programación orientada a objetos, los objetos son entidades que:

- combinan datos y de comportamiento.
- se usan para modelar entidades complejas.

In [5]:
class Persona:
  def __init__(self, altura, peso, nombre):
    # Variables de instancia, o atributos.
    self.altura = altura
    self.peso = peso
    self.nombre = nombre
  # Métodos...
  def presentarse(self):
    print(f"Hola, mi nombre es {self.nombre}")
  def saludar(self, otra_persona):
    print(f"{self.nombre} saluda a {otra_persona.nombre}")
  def comparar_altura(self, otra_persona):
    if self.altura > otra_persona.altura:
      print(f"{self.nombre} es más alto que {otra_persona.nombre}")
    elif self.altura < otra_persona.altura:
      print(f"{self.nombre} es más bajo que {otra_persona.nombre}")
    else:
      print(f"{self.nombre} tiene la misma altura que {otra_persona.nombre}")


p1 = Persona(180, 75, "Juan")
p2 = Persona(190, 85, "Pedro")

p1.presentarse()
p2.presentarse()
p1.saludar(p2)
p1.comparar_altura(p2)

Hola, mi nombre es Juan
Hola, mi nombre es Pedro
Juan saluda a Pedro
Juan es más bajo que Pedro


## Ejercicios de practica de python

1. Imprimir la suma del número actual y el anterior en una lista
2. Eliminar los primeros n caracteres de un string
3. Contar la cantidad de veces que aparece cada elemento en una lista
4. Imprimir los números de una lista que son divisibles por cinco
5. Imprimir el patrón, hasta una altura arbitraria:
```
       *
      * *
     * * *
    * * * *
```
6. Separar numeros pares e impares de un lista
7. Calcular el impuesto de un ingreso según estas reglas:

    1. Primeros 100000 pesos -> 0 por ciento
    2. 100000 pesos a 200000 pesos -> 5 por ciento,
       del exceso sobre tope mínimo de esta categoria,
       hasta el tope máximo de esta categoría.
       Más lo que corresponda en las categorías previas.
    3. 200000 pesos a 250000 pesos -> 10 por ciento
       del exceso sobre tope mínimo de esta categoria,
       hasta el tope máximo de esta categoría.
       Más lo que corresponda en las categorías previas.
    4. Más de 250000 -> 25 por ciento
       del exceso sobre tope mínimo de esta categoria,
       Más lo que corresponda en las categorías previas.

8. Dada una frase y posibles anagramas, elegir los correctos.
9. Dada la secuencia de una proteína, escribir una función que permita
   calcular la frecuencia de aparición de k-mers de la longitud pedida.
   El resultado debe ser diccionario.
10. Imprimir un gráfico tipo DotPlot para dos secuencias.
    Luego, solo mostrar las diagonales que tienen al menos cinco coincidencias.

### Resolución

1. Imprimir la suma del número actual y el anterior en una lista.

In [ ]:
l = [1, 2, 3, 4]

def ej1(n, lista):
  v = lista.index(n)
  if v:
    print("No hay un numero anterior")
    return None
  else:
    suma = n + lista[v-1]
    return suma


In [49]:
def ej1v2(lista):
  resultado = []
  for n in lista:
    if n == 0:
      resultado.append(lista[n])
    else:
      resultado.append(lista[n] + lista[n-1])
  return resultado

ej1v2([1, 2, 3, 4])

[1, 3, 5, 7]

In [53]:
lista = [7,9,5,3]

def ej1v2(lista):
  numero_anterior = 0
  resultado = []
  for n in lista:
    suma = n + numero_anterior
    numero_anterior = n
    resultado.append(suma)
  return resultado

ej1v2([1,2,3,4])

[1, 3, 5, 7]

Eliminar los primeros n caracteres de un string

In [55]:
s = "Este es un string"

" es un string"

def remover_n_caracteres(s, n):
  return s[n:]

remover_n_caracteres(s, 4)


' es un string'

Contar la cantidad de veces que aparece cada elemento en una lista

In [65]:
lista = [1, 2, 3, 1, 1, 2]


lista.count(1)

def contar_elementos(lista):
  for i in lista:
    v = lista.count(i)
    print(f"El elemento {i} aparece {v} veces")

# contar_elementos(lista)

def contar_elementos_v2(lista):
  resultado = {}
  for n in set(lista):
    resultado[n] = lista.count(n)
  return resultado

# contar_elementos_v2(lista)

def contar_elementos_v3(lista):
  resultado = {}
  for n in lista:
    if n not in resultado:
      resultado[n] = 1
    else:
      resultado[n] += 1
  return resultado

contar_elementos_v3(lista)


{1: 3, 2: 2, 3: 1}

Imprimir los números de una lista que son divisibles por cinco

In [73]:
lista = [1, 5, 20, 54]

def imprimir_divisible_por_cinco(lista):
  resultado = []
  for i in lista:
    if i % 5 == 0:
      resultado.append(i)
  return resultado

def imprimir_divisible_por_cinco_v2(lista):
  resultado = [i for i in lista if i % 5 == 0]
  return resultado

def imprimir_divisible_por_n(lista, n):
  resultado = [i for i in lista if i % n == 0]
  return resultado

imprimir_divisible_por_n(lista, 9)




[54]

Imprimir el patrón, hasta una altura arbitraria:

In [80]:
# imprimir_triangulo(3)

#  *
# * *
#* * *

def imprimir_triangulo(n):
  '''imprime un arbolito simetrico con n numeros de columna'''
  for x in range(1, n + 1):
    espacios = n - x
    palabra = ' ' * int(espacios) + '* ' * x
    print(palabra)

imprimir_triangulo(7)


      * 
     * * 
    * * * 
   * * * * 
  * * * * * 
 * * * * * * 
* * * * * * * 


Separar numeros pares e impares de un lista


In [83]:
lista = [3, 4, 8 , 12, 55]

([3, 55], [4, 8, 12])

def separar(lista):
  lista_pares = []
  lista_impares = []
  for n in lista:
    if n % 2 == 0:
      lista_pares.append(n)
    else:
      lista_impares.append(n)
  return lista_impares, lista_pares

def separar_v2(lista):
  lista_pares = [x for x in lista if x % 2 == 0]
  lista_impares = [x for x in lista if x % 2 != 0]
  return lista_impares, lista_pares

separar_v2(lista)


([3, 55], [4, 8, 12])

Calcular el impuesto de un ingreso según estas reglas:

    Primeros 100000 pesos -> 0 por ciento
    100000 pesos a 200000 pesos -> 5 por ciento
    200000 pesos a 250000 pesos -> 10 por ciento
    El resto -> 25 por ciento



150000
 - 0 > 100000
 - 0.05 * 50000

 220000
 - 0 > 100000
 - 0.05 * 100000
 - 0.1 * 20000


In [6]:

def calc_impuesto_aux(ingreso, tope_min, tope_max, percent):
  if ingreso <= tope_min:
    return 0
  exceso = min(ingreso-tope_min, tope_max)
  return exceso * percent / 100

def calcular_impuesto(ingreso):
  result = [
    calc_impuesto_aux(ingreso, 0, 100_000, 0),
    calc_impuesto_aux(ingreso, 100_000, 200_000, 5),
    calc_impuesto_aux(ingreso, 200_000, 250_000, 10),
    calc_impuesto_aux(ingreso, 250_000, float('inf'), 25),
  ]
  return sum(result)


calcular_impuesto(220000)


8000.0

Dada una frase y posibles anagramas, elegir los correctos.

In [102]:
frase =  "Istmo de Panama"
posibles_anagramas = ["Tio Sam me da pan", "Tio Sam me da queso", "Tio Samm da pena"]

#seleccionar_anagramas(frase, posibles_anagramas)

["Tio Sam me da pan", "Tio Samm da pena"]

def contar_letras(frase):
  resultado = {}
  frase = frase.lower()
  for n in set(frase):
    if n != " ":
      resultado[n] = frase.count(n)
  return resultado

def seleccionar_anagramas(frase, anagramas):
  letras_frase = contar_letras(frase)
  resultado = []
  for a in anagramas:
    letras_en_anagrama = contar_letras(a)
    if letras_frase == letras_en_anagrama:
      resultado.append(a)
  return resultado

seleccionar_anagramas(frase, posibles_anagramas)

['Tio Sam me da pan', 'Tio Samm da pena']

9. Dada la secuencia de una proteína, escribir una función que permita
   calcular la frecuencia de aparición de k-mers de la longitud pedida.
   El resultado debe ser diccionario.

In [19]:
from collections import defaultdict

def kmers(sequence:str, kmer_length:int=3) -> dict[str, float]:
  if len(sequence) < kmer_length:
    return {}
  result = defaultdict(float)
  total_kmers = 0
  for index in range(len(sequence)-kmer_length+1):
    kmer = sequence[index: index+kmer_length]
    total_kmers += 1
    result[kmer] += 1
  result = {
    kmer: float(count) / total_kmers
    for kmer, count in result.items()
  }
  return result

kmers("MQGTYKLPIMNEDEDEDEDQQQ")


{'MQG': 0.05,
 'QGT': 0.05,
 'GTY': 0.05,
 'TYK': 0.05,
 'YKL': 0.05,
 'KLP': 0.05,
 'LPI': 0.05,
 'PIM': 0.05,
 'IMN': 0.05,
 'MNE': 0.05,
 'NED': 0.05,
 'EDE': 0.15,
 'DED': 0.15,
 'EDQ': 0.05,
 'DQQ': 0.05,
 'QQQ': 0.05}

10. Imprimir un gráfico tipo DotPlot para dos secuencias.
    Luego, solo mostrar las diagonales que tienen al menos cinco coincidencias.

In [52]:
def dotplot(seq1:str, seq2: str):
  result = [
    [int(i==j) for j in seq2]
    for i in seq1
  ]
  return result

def count_in_diag(dotplot, x, y):
  counter = 0
  while dotplot[x][y] == 1 and x>=0 and y>=0:
    counter += 1
    x -= 1
    y -= 1
  return counter

def update_dotplot(dotplot, x, y, val):
  while dotplot[x][y] == 1 and x>=0 and y>=0:
    dotplot[x][y] = val
    x -= 1
    y -= 1

def clean_dotplot(dotplot:list[list[int]]) -> list[list[int]]:
  h = len(dotplot)
  w = len(dotplot[0])
  for i in range(h-1, -1, -1):
    for j in range(w-1, -1, -1):
      if dotplot[i][j]==1:
        count = count_in_diag(dotplot, i, j)
        if count >= 5:
          update_dotplot(dotplot, i, j, count)
        else:
          update_dotplot(dotplot, i, j, 0)


def print_dotplot(dotplot:list[list[int]]):
  for row in dotplot:
    print("".join("X" if col>0 else "." for col in row))

dp = dotplot("QWERTYCYCKALM", "WERTYHMQCYAIPKFGNMASCKALM")
print_dotplot(dp)
print("")
count_in_diag(dp, 3, 2)
clean_dotplot(dp)
print_dotplot(dp)

.......X.................
X........................
.X.......................
..X......................
...X.....................
....X....X...............
........X...........X....
....X....X...............
........X...........X....
.............X.......X...
..........X.......X...X..
.......................X.
......X..........X......X

.........................
X........................
.X.......................
..X......................
...X.....................
....X....................
.........................
.........................
....................X....
.....................X...
......................X..
.......................X.
........................X


In [36]:
list(range(10-1, 1-1, -1))

[9, 8, 7, 6, 5, 4, 3, 2, 1]

### Anotaciones de tipos

En las últimas versiones de python, las variables pueden ser anotadas con el
tipo que le corresponde.

La anotación de tipos sirve para:

- Dar mayor claridad al código.
- Para que herramientas externas pueden analizar y verificar la consistencia
  de tipos en el código.

In [6]:
# por ejemplo, una variable:

var1 = 1

# su puede anotar como:

var1:int = 1

In [ ]:
# una función

def eliminar_pares(numeros):
  resultado = []
  for n in numeros:
    if n%2!=0:
      resultado.append(n)
  return resultado

# Se puede anotar:

def eliminar_pares(numeros: list[int]) -> list[int]:
  resultado:list[int] = []
  for n in numeros:
    if n%2!=0:
      resultado.append(n)
  return resultado


### Construcción de listas, sets y diccionarios por comprensión.



In [7]:
# a partir de la lista1
lista1 = [1, 2, 3, 4, 5]

# quiero construir la lista de cuadrados.
cuadrados = []
for x in lista1:
  cuadrados.append(x**2)
print(cuadrados)

# Alternativamente usando comprensión de listas:
cuadrados = [x**2 for x in lista1]

[1, 4, 9, 16, 25]


In [ ]:
# a partir de la lista1
lista1 = [1, 2, 3, 4, 5]

# quiero construir la lista de cuadrados de los números paras.
cuadrados_pares = []
for x in lista1:
  if x%2==0:
    cuadrados_pares.append(x**2)
print(cuadrados_pares)

# Alternativamente usando comprensión de listas:
cuadrados_pares = [x**2 for x in lista1 if x%2==0]

[1, 4, 9, 16, 25]


In [8]:
# A partir de la lista1,
lista1 = [
  ("Q01970", "1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase beta-3"),
  ("P63104", "14-3-3 protein zeta/delta"),
  ("P60896", "26S proteasome complex subunit SEM1"),
  ("P55036", "26S proteasome non-ATPase regulatory subunit 4"),
]

# quiero armar un diccionario.
idrs = {}
for uniprot, nombre in lista1:
  idrs[uniprot] = nombre

# Alternativamente construyendolo por comprensión
idrs = {
  uniprot: nombre for uniprot, nombre in lista1
}

{'Q01970': '1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase beta-3',
 'P63104': '14-3-3 protein zeta/delta',
 'P60896': '26S proteasome complex subunit SEM1',
 'P55036': '26S proteasome non-ATPase regulatory subunit 4'}

In [1]:
# A partir de estos datos
data = [
  ("P13551", "Thermus thermophilus"),
  ("P03129", "Human papillomavirus"),
  ("P14738", "Staphylococcus aureus"),
  ("P06179", "Salmonella typhimurium"),
  ("P26477", "Salmonella typhimurium"),
  ("P56206", "Thermus thermophilus")
]

# quiero obtener el conjunto de los organismos.
organismos = set()
for uniprot, orgn in data:
  organismos.add(orgn)

# alternativamente construyendo el conjunto por comprensión
organismos = {orgn for uniprot, orgn in data}

### map, filter y reduce

map(), filter() y reduce() son tres funciones que permiten manipular estructuras de
datos que pueden ser iteradas, por ejemplo las listas.




- Función map(función, iterable):

  - map() aplica una función a cada elemento de un iterable (como una lista) y
  devuelve un iterador que produce los resultados.
  - Toma dos argumentos: la función que se aplicará y el iterable sobre el cual
  se aplicará esa función.
  - La función pasada como primer argumento será aplicada a cada elemento del
  iterable, y el resultado será un nuevo iterador que produce los resultados de
  aplicar la función a cada elemento.
  - Por ejemplo:
  ```python
    lista = [1, 2, 3, 4, 5]
    cuadrados = map(lambda x: x**2, lista)
    print(list(cuadrados))  # Salida: [1, 4, 9, 16, 25]
  ```



- Función filter(función, iterable):

  - filter() crea un iterador que devuelve los elementos de un iterable para los
    cuales una función devuelve True.
  - Toma dos argumentos: la función que se aplicará y el iterable sobre el cual
    se aplicará esa función.
  - La función pasada como primer argumento debe devolver True o False. Si
    devuelve True, el elemento se incluirá en el iterador de salida; de lo
    contrario, se omitirá.
  - Por ejemplo:
  ```python
    lista = [1, 2, 3, 4, 5]
    impares = filter(lambda x: x % 2 != 0, lista)
    print(list(impares))  # Salida: [1, 3, 5]
  ```



- Función reduce(función, iterable, valor_inicial):

  - reduce() aplica repetidamente una función a los elementos del iterable,
    reduciendo así la secuencia a un solo valor.
  - Toma tres argumentos: la función que se aplicará, el iterable sobre el cual
    se aplicará esa función y un valor inicial opcional.
  - La función pasada como primer argumento debe aceptar dos argumentos y
    devolver un resultado. Este resultado se utilizará como el primer argumento
    en la próxima llamada a la función, junto con el siguiente elemento del iterable.
  - Es necesario importar reduce del módulo functools.
  - Por ejemplo:
  ```python
    from functools import reduce
    lista = [1, 2, 3, 4, 5]
    suma = reduce(lambda x, y: x + y, lista)
    print(suma)  # Salida: 15
  ```


### Piping

Piping es la transformación de datos a traves de operaciones encadenadas.
Cada operación toma los resultados de un paso previo, hace una transformacíon
y los envía a la salida de datos para que otra operación continue.


Datos de partida -> operación 1 -> operación 2 -> Resultado final.

El python los pipes no son nativos del lenguage pero se pueden utilzar con el
paquete "pipe".

In [68]:
import pipe

# data contiene datos de algunas proteinas desordenadas: El uniprot accession,
# El nombre de la proteína, la longitud de la proteína y el contenido porcentual
# de desorden
data = [
  ("P13551", "Elongation factor G", "Thermus thermophilus", 691, 8.54),
  ("P03129", "Protein E7", "Human papillomavirus type 16", 98, 52.04),
  ("P14738", "Fibronectin-binding protein A", "Staphylococcus aureus", 1018, 12.77),
  ("P06179", "Flagellin", "Salmonella typhimurium", 495, 21.21),
  ("P26477", "Negative regulator of flagellin synthesis", "Salmonella typhimurium ", 97, 100.00),
  ("P56206", "Glycine--tRNA ligase", "Thermus thermophilus", 506, 17.00),
  ("P02929", "Protein TonB", "Escherichia coli", 239, 20.50),
  ("P27001", "Phenylalanine--tRNA ligase alpha subunit", "Thermus thermophilus", 350, 28.86),
  ("P11409", "Modification methylase PvuII", "Proteus hauseri", 336, 11.31),
]

# quiero transformar estos datos:
# - eliminar las del genero Salmonella y Escherichia.
# - Calcular la cantidad de posiciones desordenadas y agregarlo a los datos existentes.
# - Finalmente eliminarlas que tengon menos de 100 posiciones desordenadas.

resultado = filter(
  lambda x: x[5]>=100,
    map(
    lambda x: (*x, round(x[3]*x[4]/100)),
    filter(
      lambda x: not any(y in x[2] for y in ["Escherichia", "Salmonella"]),
      data
    )
  )
)
list(resultado)

[('P14738',
  'Fibronectin-binding protein A',
  'Staphylococcus aureus',
  1018,
  12.77,
  130),
 ('P27001',
  'Phenylalanine--tRNA ligase alpha subunit',
  'Thermus thermophilus',
  350,
  28.86,
  101)]

In [69]:
# Alternativamente

r1 = filter(
  lambda x: not any(y in x[2] for y in ["Escherichia", "Salmonella"]),
  data
)
r2 = map(lambda x: (*x, round(x[3]*x[4]/100)), r1)
resultado = filter(lambda x: x[5]>=100, r2)
list(resultado)

[('P14738',
  'Fibronectin-binding protein A',
  'Staphylococcus aureus',
  1018,
  12.77,
  130),
 ('P27001',
  'Phenylalanine--tRNA ligase alpha subunit',
  'Thermus thermophilus',
  350,
  28.86,
  101)]

In [71]:
# usando pipes
from pipe import map, filter
resultado = list(
  data
    | filter(lambda x: not any(y in x[2] for y in ["Escherichia", "Salmonella"]))
    | map(lambda x: (*x, round(x[3]*x[4]/100)))
    | filter(lambda x: x[5]>=100)
)
resultado

[('P14738',
  'Fibronectin-binding protein A',
  'Staphylococcus aureus',
  1018,
  12.77,
  130),
 ('P27001',
  'Phenylalanine--tRNA ligase alpha subunit',
  'Thermus thermophilus',
  350,
  28.86,
  101)]

## Introducción a Numpy

- Computación numérica
- Centrada en Arrays multidimensionales
- Referencia de la API:
  - https://numpy.org/doc/stable/reference/index.html

### Crear Arrays

- np.array
- np.zeros
- np.ones
- np.empty
- np.arange
- np.linspace
- np.identity

In [17]:
import numpy as np

arr1 = np.array([[1, 2, 3], [6,7,8]])
print(arr1)

arr2 = np.ones((2,3))
print(arr2)

print(arr2 * arr1)

print(np.empty((2, 3)))

np.arange(
  start = 1,
  stop = 20,
  step = 4
)

np.linspace(
  np.array([0, 1]),
  np.array([1, 11]),
  3
)

np.identity(4)

[[1 2 3]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [6. 7. 8.]]
[[1. 2. 3.]
 [6. 7. 8.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Cambiar forma de un array

- reshape
- transpose



In [33]:
arr1 = (
  np.array(range(12))
    .reshape((3, 4))
    .transpose()
)
print(arr1)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Funciones universales

- Funciones que se aplican a Arrays de cualquier dimension
- por elemento

Por ejemplo:

- numpy.add
- numpy.matmul
- numpy.multiply
- numpy.equal
- numpy.logical_and

In [65]:
arr1 = (
  np.array(range(12))
    .reshape((3, 4))
)

np.add(arr1, arr1) # igual a arr1 + arr1

np.matmul(arr1, arr1.transpose()) # igual arr1 @ arr1.transpose()

np.multiply(arr1, arr1) # arr1 * arr1

np.equal(arr1, arr1 * 0) # igual arr1 == arr1

np.logical_and(arr1>0, arr1%2==0) # igual  (arr1 > 0) & (arr1 %2==0)


array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

### Subseteo de arrays

In [81]:
arr1 = np.array(range(12)).reshape(3,4)

print(arr1[1, 0])


4


In [89]:
arr1 = np.array(list("CTACTGATGCCTGACTG"))
index = [
  [0, 1, 2],
  [1, 2, 3],
  [2, 3, 4],
  [3, 4, 5]
]
arr1[index]

array([['C', 'T', 'A'],
       ['T', 'A', 'C'],
       ['A', 'C', 'T'],
       ['C', 'T', 'G']], dtype='<U1')

## Introducción a Pandas

Permite trabajar con:
- Series de datos (Series)
- Datos tabulares (Dataframe)

Referencia:
- https://pandas.pydata.org/docs/reference/index.html
- Cheat Sheet : https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

### Crear Series y DataFrame

- Dataframe
  - desde dicctionario
  - desde listas
  - desde un archivo
- Series
  - Desde una lista

### Cambiar la forma de un Dataframe

- shape
- melt
- pivot
- concat

### Subsetting

- Seleccionar filas
- Seleccionar columas
- Seleccionar filas y columnas

### Combinar Dataframes
- merge

### Resumen de datos

- value_counts
- describe

### Agrupar datos

- groupby
- aggregate

## Introducción a Matplotlib

- Creación de gráficos
- Referencia
  - https://matplotlib.org/stable/api/index.html
- Ejemplos:
  - https://matplotlib.org/stable/gallery/index.html

### Crear plots y axes

### Cambiar texto de un plot

### Anotar un plot

## Introducción a Scipy

- Computación científica en python.
  - Estadística
  - Métodos de optimization
  - Resolución de ecuaciones diferenciales
  - etc.
- Referencia:
  - https://docs.scipy.org/doc/scipy/reference/stats.html

- Distribuciones de probabilidad
    - continuas
    - multivariadas
    - discretas
- Estadísticos de resumen
- Correlación
- Test estadísticos
- Ajuste de datos a una distribución



## Introducción a SymPy

- Computación simbólica
- Referencia:
  - https://www.sympy.org/en/index.html


### Cálculo de derivadas

### Cálculo de integrales

### Resolución de ecuaciones

## 